services:
  maildev:
    container_name: ledup-test-maildev
    image: ledup/maildev:2.2
    hostname: maildev
    ports:
      - "1080:80"
    extends:
        file: $HOME/.led/docker-base.yaml
        service: localuser
